version: '3.7'
services:
  main:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: main
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      BASE_PWD: ${BASE_PWD}
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ${BASE_PWD}:/app
      - pscr_docker_data_cache_node_modules:/app/node_modules:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    command: >
      sh -c '${RERUN_COMPOSE_COMMAND}'
    networks:
      - pscr_dev
    ports:
      - 9226:9229
volumes:
  pscr_docker_data_cache_node_modules:
    name: pscr_docker_data_cache_node_modules
networks:
  pscr_dev:
    name: pscr_dev
    driver: bridge
